### ISSUE TITLE
PS5 support?

### ISSUE THREAD

**Issue by jasii** [Gkiokan/hb-store-cdn-cli-server#11]
Trying to get this working on the PS5 with the latest HB Store from pkg-zone.com

I got it running in a docker container, but I'm getting "Update has FAILED" within HB Store app after changing the IP to my server IP

Here's the error in the loader logs

```
[STORE_GL_Loader:loader_rooted:426] ----- INI FOUND ---
CDN = http://192.168.1.20:6449
Secure_Boot = 1
temppath = /user/app/NPXS39041/downloads
TTF_Font = /mnt/sandbox/pfsmnt/NPXS39041-app0/assets/fonts/font.ttf
auto_install = 1
Legacy_install_prog = 0
auto_load_cache = 1
[STORE_GL_Loader:loader_rooted:435] ----- CDN Url = http://192.168.1.20:6449 ---
[STORE_GL_Loader:loader_rooted:442] ----- Ping Successful ---
prog: 0
prog: 0
prog: 0
prog: 0
prog: 0
prog: 0
prog: 0
prog: 100
prog: 100
prog: 100
prog: 100
[STORE_GL_Loader:loader_rooted:449] ----- Downloaded remote.md5 ---
[STORE_GL_Loader:loader_rooted:451] ----- CheckForUpdate() ---
[STORE_GL_Loader:checkForUpdate:271] ----- ELF exists ---
[STORE_GL_Loader:checkForUpdate:272] ----- Comparing Hashs ---
Update Required, Press OK to Update the App
sceMsgDialogTerminate = -2135425021
sceMsgDialogInitialize = 0
Download: 0 / 0
Download: 0 / 0
Download: 0 / 0
Download: 0 / 0
Download: 0 / 0
Download: 0 / 0
Download: 0 / 0
Download: 0 / 0
Download: 155 / 155
Download: 155 / 155
Download: 155 / 155
Download: 155 / 155
Update has FAILED. Please reinstall the latest HB-Store
The Store Loader has encountered an error

For more info check: /user/app/NPXS39041/logs/loader.log The App will now Close
```

Here's the relevant store_api logs

```
[HTTP] User Agent set to StoreHAX/GL-PS5-0x403
httpresponsecode: 200
sceStoreDownloadUsingCurl("StoreHAX/GL-PS5-0x403", "http://192.168.1.20:6449/store.db", "/user/app/NPXS39041/store_downloaded.db", 0x800c21af0) | API version: 0x1004
Downloading: http://192.168.1.20:6449/store.db | 0x803bfdd0 | 0x8040c0e0
curl_easy_init: 0x200072260
[HTTP] User Agent set to StoreHAX/GL-PS5-0x403
httpresponsecode: 200
sceStorePingTest("StoreHAX/GL-PS5-0x4030000", "http://192.168.1.20:6449") | API version: 0x1004
server http://192.168.1.20:6449
[HTTP] User Agent set to StoreHAX/GL-PS5-0x4030000
Download size: 204800

pingtest returned 0
sceStoreDownloadUsingCurl("StoreHAX/GL-PS5-0x4030000", "http://192.168.1.20:6449/update/remote.md5", "/user/app/NPXS39041/remote.md5", 0x405980) | API version: 0x1004
Downloading: http://192.168.1.20:6449/update/remote.md5 | 0x803bfdd0 | 0x8040c0e0
curl_easy_init: 0x200054620
[HTTP] User Agent set to StoreHAX/GL-PS5-0x4030000
httpresponsecode: 200
sceStoreDownloadUsingCurl("StoreHAX/GL-PS5-0x4030000", "http://192.168.1.20:6449/update/store.prx", "/system/common/lib/store.prx", 0x404480) | API version: 0x1004
Downloading: http://192.168.1.20:6449/update/store.prx | 0x803bfdd0 | 0x8040c0e0
curl_easy_init: 0x200054620
[HTTP] User Agent set to StoreHAX/GL-PS5-0x4030000
httpresponsecode: 404
```

I'm getting a 404 on http://192.168.1.20:6449/update/store.prx

Am I missing the store.prx file?
I have all the latest downloaded bin files from the cli script, specifically the files here https://github.com/LightningMods/PS4-Store/releases

I even tried extracting the PS5_Update_files.zip and placed that in a folder called update with in the /app/bin folder

**Comment by Gkiokan** [comment]
As the Store works the same way on the ps4 as on the ps5 I assume it must be working.  

There are a couple binary files that needs to be initiated though the app that will be served to the hb-store to work properly.  

I think the issue relies on the different store.prx file that the ps5 needs and the code does only serve the ps4 one. 
For the ps4 we hadn't that file and it will not be served just because it is in the update folder.  

The fix for this would be to implement a custom route to serve the store.prx file, too.  
Lemme get my hands on quickly. brb

**Comment by Gkiokan** [comment]
@jasii I just did a pre-release for ps5 support which should work.  
Could you try the new release out? 
[v1.4.1 Pre-Release](https://github.com/Gkiokan/hb-store-cdn-cli-server/releases/tag/v1.4.1)

**Comment by jasii** [comment]
> @jasii I just did a pre-release for ps5 support which should work.  
> Could you try the new release out? 
> [v1.4.1 Pre-Release](https://github.com/Gkiokan/hb-store-cdn-cli-server/releases/tag/v1.4.1)

I'll give it a shot tonight and get back to you.

Thank you

**Comment by jasii** [comment]
1.4.1 is working on PS5 HB Store!

Thank you so much

Also I made a dockerfile, well, ChatGPT did and I got an image up on my docker hub. The image is massive, I'm going to try to shrink it down as it's running on Ubuntu 22 base right now. It's working, but you need to go into the console first and run the download-bin command.

jojojoseph/hb-store-cdn-cli-server:1.4.1

**Comment by Gkiokan** [comment]
Thanks for the reply. Glad it works on ps5 seemslely.  

If you setup your docker file accordingly you can have the binary working out of the box without running the exec command.  
If you may have seen this Project is also added on [RetroNAS](https://github.com/danmons/retronas).  
You can read the ps4 discussion [here](https://github.com/danmons/retronas/issues/177https://github.com/danmons/retronas/issues/177)
  
If you run the binary with the `start` parameter it does actually download the bin and starts then preconfigured the server. The only thing that you need to provide is the config file.
