### ISSUE TITLE
No arm64 Support?

### ISSUE THREAD

**Issue by pcfreaxx** [Gkiokan/hb-store-cdn-cli-server#2]
Hi. I tried zu run it in my rk3399 device. Orange Pi 4b/Armbian Bullseye but i cant get it run.
Will there come Support for?

**Comment by Gkiokan** [comment]
Can't test the build for arm right now. I can add it to the build script once I get time for it.   
Probably the next weeks earliest.  
 
If you can't wait you can try to build it on your own.  
```
git clone https://github.com/Gkiokan/hb-store-cdn-cli-server.git && cd hb-store-cdn-cli-server && npm i && npm run build
```

after that you should have a `release` folder with a binary that you can start.

**Comment by Gkiokan** [comment]
If you would like to support this project I may put it higher on priority. But for now I have other priorities.  
So either use the solution provided before or be patient please.  

Thanks.
