### ISSUE TITLE
Could we get some command line options like to load a config and auto start the server?

### ISSUE THREAD

**Issue by steve51184** [Gkiokan/hb-store-cdn-cli-server#4]
I think that'd be really cool.. one command to start the server and then close it via ctrl+c etc :)

**Comment by Gkiokan** [comment]
I think you can do that already? But not the direct autostart. It depends on the config if it exists.  
But yea an autostart feature would be somehow usefull.  

I will take that into account for the next update.

**Comment by Gkiokan** [comment]
I just checked it. There is already a start command to start the server with a pre-config.  
First run the Setup to have a configuration file.  
Then on the upcoming starts you can use ` ./hb-store-cdn-cli-server start` to start it directly. 

<img width="819" alt="image" src="https://user-images.githubusercontent.com/7249224/184533147-e37eac4f-a324-45f6-bc9b-26f4790563e1.png">
