### ISSUE TITLE
Speeds slow?

### ISSUE THREAD

**Issue by steve51184** [Gkiokan/hb-store-cdn-cli-server#5]
Is there anyway to improve the DL speed? I have 100mbits in both directions but feels like 10mbits :(

**Comment by Gkiokan** [comment]
There are a couple of videos about optimizing Transferspeed between host <> ps4.  
This is a limitation of your local infrastructure. The application does send all data as fast as possible, but your configuration may be the bottleneck.   
 
Checkout the Videos from Modern Warfare, he does some explanations on it.

**Comment by Gkiokan** [comment]
Have a look into this:  
[Remote Package Sender V2 | Detailed Tutorial | Windows | Mac | High Speeds | Tutorial](https://www.youtube.com/watch?v=RyKUm5rndPQ) 

[Improving the Speed of the Remote Package Installer](https://www.youtube.com/watch?v=v04zI5SD07k)

**Comment by steve51184** [comment]
"use ethernet" isn't an option for a remote server though?

**Comment by Gkiokan** [comment]
If you have a remote VPS Server then the options still applies to your local network. 
In case if you have a bottleneck you need to figure out where your bottleneck is.  

This is more an Network Infrastructure Question and has less todo with the app itself.

**Comment by steve51184** [comment]
I have wired fiber internet at home which can do 100mbits and a server with 1gbits 

I've done speed tests and I can indeed pull 100mbits from my server

I do it all the time via FTP to get my games from my server to my computer/external drive so I can install them on my PS4 and again I always hit 100mbits

But with this app under the same conditions I'm getting maybe 10% that speed so it very much is a problem with this app or the hb-store app

Can multi-threaded transfers be an option?

**Comment by Gkiokan** [comment]
Actually you are the first one having this issue. I will talk to LM about that and see what we can do.  
Meanwhile you could also checkout the [PKG-zone discord server](https://discord.gg/cUSdgfEb6Y) where we are located at.  
 
The HB-Store itself does download a file in 80mb chunks on it's own thread.  
The Server does just send the file as response stream which should use all available bandwidth.  
 
On which host does the server application run? Did you try another host in your network?

**Comment by Gkiokan** [comment]
There is something that just comes in my mind. Are you using more then 4 concurrent downloads?  
I have planed a multi threaded option to supercharge the application itself. For now it is limited to the defaults.  
 
But this is something that will come later in the end of the year.  
You could try to set your env variable of `UV_THREADPOOL_SIZE ` to a higher size, like 64, and try again.
