### ISSUE TITLE
Covers are not being downloaded

### ISSUE THREAD

**Issue by filipdadgar** [Gkiokan/hb-store-cdn-cli-server#9]
Hi,

Thank you for awesome work!
A small issue that I face is that all icons/thumbnails are the generic one and are not being updated/downloaded.

Is there a specific flag I need to add to the config file?

For reference I run the store inside kubernetes through a self-made dockerimage: https://github.com/filipdadgar/hb-store/blob/main/Dockerfile

Connection and functionality works, but the covers are giving me OCD. :)

Thanks in advance!

**Comment by Gkiokan** [comment]
Can you check the HB-Store Logs which URL's are being tried to resolve for the covers?  

Or just check the store.db that is generated by the server and try to resolve the URL.  
I guess if there is a missing host:port forwarding this may be run into 404 then.  
  
Generated store.db can be found at serverIP:port/store.db, it's a sqlite3 DB.

**Comment by Gkiokan** [comment]
Btw, I just checked your DockerImage. Looks interesting. Actually you can omit the binary download part and just call the server with start parameter, because it will now check for updates on every start.  

Also you can use now `check-bin` for update binaries if available or `download-bin` to force re-download the binaries. 

Once you checkout the cover URL's I can have a look into it if there is an application error. But as I said I guess it's just a routing/port/URI issue at the first glance. Can't test the DockerImage right now, being quite busy currently. Sorry for that.

**Comment by filipdadgar** [comment]
Thank you for looking into this! 

This is a small extract from reading store.db file:

`root@node1:/app/bin# cat store.db
���*�#tablehomebrewshomebrewsCREATE TABLE `homebrews` (`pid`, `id`, `name`, `desc`, `image`, `package`, `version`, `picpath`, `desc_1`, `desc_2`, `ReviewStars`, `Size`, `Author`, `apptype`, `pv`, `main_icon_path`, `main_menu_pic`, `releaseddate`, `number_downloads`, `github`, `video`, `twitter`)^!������������������������|vpjdCUSA00135BATMAN™: ARKHAM KNIGHThttp://localhost:8888/Batman.Arkham.Knight.PS4-DUPLEX/Batman.Arkham.Knight.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/Batman.Arkham.Knight.PS4-DUPLEX/Batman.Arkham.Knight.PS4-DUPLEX.pkg01.00/user/app/NPXS39041/storedata/CUSA00135.pngCustom Rating48.97 GBHB-Store CDNHB Game5.05+http://localh'%�c!CUSA24653Alan Wake Remasteredhttp://localhost:8888/Alan.Wake.Remastered.Incl.Update.v1.03.PS4-DUPLEX/Alan.Wake.Remastered.Update.v1.03.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/Alan.Wake.Remastered.Incl.Update.v1.03.PS4-DUPLEX/Alan.Wake.Remastered.Update.v1.03.PS4-DUPLEX.pkg01.03/user/app/NPXS39041/storedata/CUSA24653.pngCustom Rating28.92 GBHB-Store CDNHB Game5.05+http://localhost:8888/Alan.Wake.Remastered.Incl.Update.v1.03.PS4-DUPLEX/Alan.Wake.Remastered.Update.v1.03.PS4-DU'%�wc!CUSA24653Alan Wake Remasteredhttp://localhost:8888/Alan.Wake.Remastered.Incl.Update.v1.03.PS4-DUPLEX/Alan.Wake.Remastered.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/Alan.Wake.Remastered.Incl.Update.v1.03.PS4-DUPLEX/Alan.Wake.Remastered.PS4-DUPLEX.pkg01.00/user/app/NPXS39041/storedata/CUSA24653.pngCustom Rating29.95 GBHB-Store CDNHB Game5.05+http://localhost:8888/Alan.Wake.Remastered.Incl.Update.v1.03.PS4-DUPLEX/Alan.Wake.Remastered.PS4-DUPLEX.pkg/icon0.png/user/app/NPXS39041/'�mc!CUSA17267AO Tennis 2http://localhost:8888/AO.Tennis.2.Incl.Update.v1.06.PS4-DUPLEX/AO.Tennis.2.Update.v1.06.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/AO.Tennis.2.Incl.Update.v1.06.PS4-DUPLEX/AO.Tennis.2.Update.v1.06.PS4-DUPLEX.pkg01.06/user/app/NPXS39041/storedata/CUSA17267.pngCustom Rating2.26 GBHB-Store CDNHB Game5.05+http://localhost:8888/AO.Tennis.2.Incl.Update.v1.06.PS4-DUPLEX/AO.Tennis.2.Update.v1.06.PS4-DUPLEX.pkg/icon0.png/user/app/NPXS39041/storedata/CUSA17267.png201'�Sc!CUSA17267AO Tennis 2http://localhost:8888/AO.Tennis.2.Incl.Update.v1.06.PS4-DUPLEX/AO.Tennis.2.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/AO.Tennis.2.Incl.Update.v1.06.PS4-DUPLEX/AO.Tennis.2.PS4-DUPLEX.pkg01.00/user/app/NPXS39041/storedata/CUSA17267.pngCustom Rating8.81 GBHB-Store CDNHB Game5.05+http://localhost:8888'%�Ac!CUSA34388God of War Ragnarökhttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0200-V0100-CyB1K.pkg/icon0.pnghttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0200-V0100-CyB1K.pkg02.00/user/app/NPXS39041/storedata/CUSA34388.pngCustom Rating19.56 GBHB-Store CDNHB Game5.05+http://localhost:8888/EP9000-'%�Ac!CUSA34388God of War Ragnarökhttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0100-V0100-CyB1K.pkg/icon0.pnghttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0100-V0100-CyB1K.pkg01.00/user/app/NPXS39041/storedata/CUSA34388.pngCustom Rating90.55 GBHB-Store CDNHB Game5.05+http://localhost:8888/EP9000-'�Yc!CUSA28863ELDEN RING™http://localhost:8888/ELDEN.RING_CUSA28863_v1.10_BACKPORT_5.05-6.72-7.xx-8.0x_OPOISSO893.pkg/icon0.pnghttp://localhost:8888/ELDEN.RING_CUS�xqjcUvN.10_BACKPORT_5.05-6.72-7.xx-8.0x_OPOISSO893.pkg01.10/user/app/NPXS39041/storedata/CUSA28863.pngCustom Rating8.84 GBHB-Store CDNHB Ga �L�F�@�9�2,�%����
G
 @
,+$
 C
'%�ScCUSA00135BATMAN™: ARKHAM KNIGHThttp://localhost:8888/Batman.Arkham.Knight.PS4-DUPLEX/Batman.Arkham.Knight.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/Batman.Arkham.Knight.PS4-DUPLEX/Batman.Arkham.Knight.PS4-DUPLEX.pkg01.00/user/app/NPXS39041/storedata/CUSA00135.pngCustom Rating48.97`

I find the weird symbols worry some, but it might be by design?
I cannot see anything about it having port issues, or at least not in the container log. The egress traffic to internet is open so container/pod to internet trafffic shouldnt be a problem. 

Added the k8 manifest file to the repo as well if you are interested in checking it out:
https://github.com/filipdadgar/hb-store/blob/main/hb-store.yaml


> Btw, I just checked your DockerImage. Looks interesting. Actually you can omit the binary download part and just call the > server with start parameter, because it will now check for updates on every start.

> Also you can use now check-bin for update binaries if available or download-bin to force re-download the binaries.

Can you please elaborate on this, which binary are you referring to? The cli one?

Best and thanks again,
Filip

**Comment by filipdadgar** [comment]
Oh, saw the new release and updated the dockerfile.

I can now in store.db is connecting to following http://192.168.123.176/storedata/lraid.png.. but that ip isnt responding.

**Comment by Gkiokan** [comment]
I think you have to open the store.db with a sqlite3 browser to see the correct value of it.   
I never tried to cat on a db file. Could you try that?  

The Images URL should be actually in the format of http://ip:port/... actually the values from the config.ini.  
I can look into that on my local machine again to verify, but to check this quicker, can you try to run the server on your machine and check if that works correctly and compare whats going wrong on docker vs local? 
I am right now busy with dissambling my KORG Trinity and this may take a couple days. 

For the binary, ye the cli one whatever it is then called for you after building it with `npm run build` or the released one should work, too. I am on node v14.17.x if this does matter for you to build the project. Not sure about other versions but on retroNAS it is even build with node v12 and seems to work fine. Later versions may have deprecations.

**Comment by Gkiokan** [comment]
> http://localhost:8888/AO.Tennis.2.Incl.Update.v1.06.PS4-DUPLEX/AO.Tennis.2.PS4-DUPLEX.pkg01.00/user/app/NPXS39041/storedata/CUSA17267.pngCustom Rating8.81 GBHB-Store CDNHB Game5.05+http://localhost:8888'%�Ac!CUSA34388God of War Ragnarökhttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0200-V0100-CyB1K.pkg/icon0.pnghttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0200-V0100-CyB1K.pkg02.00/user/app/NPXS39041/storedata/CUSA34388.pngCustom Rating19.56 GBHB-Store CDNHB Game5.05+http://localhost:8888/EP9000-'%�Ac!CUSA34388God of War Ragnarökhttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0100-V0100-CyB1K.pkg/icon0.pnghttp://localhost:8888/EP9000-CUSA34388_00-GOWRAGNAROK00000-A0100-V0100-CyB1K.pkg01.00/user/app/NPXS39041/storedata/CUSA34388.pngCustom Rating90.55 GBHB-Store CDNHB Game5.05+http://localhost:8888/EP9000-'�Yc!CUSA28863ELDEN RING™http://localhost:8888/ELDEN.RING_CUSA28863_v1.10_BACKPORT_5.05-6.72-7.xx-8.0x_OPOISSO893.pkg/icon0.pnghttp://localhost:8888/ELDEN.RING_CUS��xqjcUvN.10_BACKPORT_5.05-6.72-7.xx-8.0x_OPOISSO893.pkg01.10/user/app/NPXS39041/storedata/CUSA28863.pngCustom Rating8.84 GBHB-Store CDNHB Ga �L�F�@�9�2,�%���� G @ ,+$ C '%�ScCUSA00135BATMAN™: ARKHAM KNIGHThttp://localhost:8888/Batman.Arkham.Knight.PS4-DUPLEX/Batman.Arkham.Knight.PS4-DUPLEX.pkg/icon0.pnghttp://localhost:8888/Batman.Arkham.Knight.PS4-DUPLEX/Batman.Arkham.Knight.PS4-DUPLEX.pkg01.00/user/app/NPXS39041/storedata/CUSA00135.pngCustom Rating48.97`
> 

Just by looking at this it seems like it builds the store.db with the IP of localhost which is wrong. It must be the IP of the docker container in your case. How does your config.ini looks like?

**Comment by filipdadgar** [comment]
You are absolutely right! Fixed this by following change in Dockerfile:

ARG host=ps4repo.mydomain.com # I have internal DNS setup, for others a designated IP should work. Localhost is no good!
ARG port=8888
ARG base=/repo

RUN echo "host="$host >> /app/config.ini
RUN echo "port="$port >> /app/config.ini
RUN echo "basePath=/repo" >> /app/config.ini
RUN echo "binVersion=4.31" >> /app/config.ini

Happy me, it works and super thanks!

**Comment by Gkiokan** [comment]
Glad to hear you got it work.  
Btw, you can omit the downloading a fixed binary version from LM's repo because in case of an update it will be not valid anymore.  But it's fine for now. Refinings can be always added later. 

As I said and stated in the new readme, the latest version does a check / download of binaries with  the `start` param if it wasn't done before.  

Once you have fixed that I can put your Dockerfile in the Readme for reference, too.

**Comment by filipdadgar** [comment]
Fixed! Updated dockfile and the k8 manifest file has been tested as well. :)

**Comment by Gkiokan** [comment]
`RUN echo "binVersion=4.31" >> /app/config.ini`
should be 
`RUN echo "binVersion=0.00" >> /app/config.ini`. 
for the initial build, as i only check the binary version that has been pushed from the update process.  

Not the best I know. I will fix that in the next update and also add the watcher so any changes of the basePath will be reflected immediatelly without restarting the server.

**Comment by filipdadgar** [comment]
Fixed the binVersion.

A question about this:
/app/hb-store-cdn-cli-server-linux check-bin && /app/hb-store-cdn-cli-server-linux start

I understand the check-bin is run everytime start is used? If so then the check-bin step could be removed I guess.

**Comment by Gkiokan** [comment]
Correct. The `check-bin` is only in case you want to trigger the underlying method without starting the interactive menu.   

It should be fine if you only start the app as it will first check the binaries for updates and then starts the server.

**Comment by filipdadgar** [comment]
Thanks! Will make a last update to the dockerfile now.
